export const bebidas = [
  {
    aguaSemGas: {
      id: 1,
      name: 'Água sem gás',
      type: 'sem álcool',
      price: 5,
      img: 'imgg',
    },
    aguaComGas: {
      id: 2,
      name: 'Água com gás',
      type: 'Águas',
      price: 5.5,
      img: 'imgg',
    },
    H2OH: {
      id: 3,
      name: 'H2OH',
      type: 'Refrigerantes',
      price: 6,
      img: 'imgg',
    },
    cocaCola: {
      id: 4,
      name: 'Coca-Cola',
      type: 'Refrigerantes',
      price: 6,
      img: 'imgg',
    },
    cocaColaZero: {
      id: 5,
      name: 'Coca-Cola Zero',
      type: 'Refrigerantes',
      price: 6,
      img: 'imgg',
    },
    guarana: {
      id: 6,
      name: 'Guaraná Antáctica',
      type: 'Refrigerantes',
      price: 6,
      img: 'imgg',
    },
    guaranaZero: {
      id: 7,
      name: 'Guaraná Antáctica Zero',
      type: 'Refrigerantes',
      price: 6,
      img: 'imgg',
    },
    aguaTonica: {
      id: 8,
      name: 'Água Tônica',
      type: 'Refrigerantes',
      price: 6,
      img: 'imgg',
    },
    brahma: {
      id: 9,
      name: 'Brahma',
      type: 'Cervejas',
      price: 6,
      img: 'imgg',
    },
    brahmaZero: {
      id: 10,
      name: 'Brahma Zero',
      type: 'Cervejas',
      price: 6,
      img: 'imgg',
    },
    brahmaDuploMalte: {
      id: 11,
      name: 'Brahma Duplo Malte',
      type: 'Cervejas',
      price: 7,
      img: 'imgg',
    },
    stella: {
      id: 12,
      name: 'Stella',
      type: 'Cervejas',
      price: 8,
      img: 'imgg',
    },
    becks: {
      id: 13,
      name: /Beck's/,
      type: 'Cervejas',
      price: 9,
      img: 'imgg',
    },
    heineken: {
      id: 14,
      name: 'Heineken',
      type: 'Cervejas',
      price: 9.5,
      img: 'imgg',
    },
    hoegaarden: {
      id: 15,
      name: 'Hoegaarden',
      type: 'Cervejas Artesanais',
      price: 17.9,
      img: 'imgg',
    },
    colorado: {
      id: 16,
      name: 'Colorado Ribeirão',
      type: 'Cervejas Artesanais',
      price: 19.9,
      img: 'imgg',
    },
    hocusPocusOrange: {
      id: 17,
      name: 'Hocus Pocus Orange Sunshine',
      type: 'Cervejas Artesanais',
      price: 24.9,
      img: 'imgg',
    },
    hocusPocusMagic: {
      id: 18,
      name: 'Hocus Pocus Magic Trap',
      type: 'Cervejas Artesanais',
      price: 33.9,
      img: 'imgg',
    },
    hocusPocusPineapple: {
      id: 19,
      name: 'Hocus Pocus Pineapple',
      type: 'Cervejas Artesanais',
      price: 33.9,
      img: 'imgg',
    },
    hocusPocusOrangeInterestellar: {
      id: 20,
      name: 'Hocus Pocus Interestellar',
      type: 'Cervejas Artesanais',
      price: 36.9,
      img: 'imgg',
    },
    GT: {
      id: 21,
      name: 'GT',
      type: 'Alcoolicos',
      price: 15,
      img: 'imgg',
    },
    redbull: {
      id: 22,
      name: 'RedBull',
      type: 'Energéticos',
      price: 15,
      img: 'imgg',
    },
    caipirinha: {
      id: 23,
      name: 'Caipirinha',
      type: 'Drinks',
      price: 20,
      img: 'imgg',
    },
    caipivodka: {
      id: 24,
      name: 'Caipivodka',
      type: 'Drinks',
      price: 25,
      img: 'imgg',
    },
    ginTonica: {
      id: 25,
      name: 'Gin Tônica',
      type: 'Drinks',
      price: 30,
      img: 'imgg',
    },
    gabriela: {
      id: 26,
      name: 'Gabriela',
      type: 'Doses',
      price: 30,
      img: 'imgg',
    },
    doseVodka: {
      id: 27,
      name: 'Dose de Vodka',
      type: 'Doses',
      price: 30,
      img: 'imgg',
    },
    doseAbsolut: {
      id: 28,
      name: 'Dose de Absolut',
      type: 'Doses',
      price: 30,
      img: 'imgg',
    },
  },
]

export const burgers = [
  {
    sambaDeRoda: {
      id: 1,
      name: 'Samba de Roda',
      type: 'Costela',
      price: 22.9,
      img: 'imgg',
    },
    gafieira: {
      id: 2,
      name: 'Gafieira',
      type: 'Costela',
      price: 22.9,
      img: 'imgg',
    },
    galoCanto: {
      id: 3,
      name: 'Galo Cantô',
      type: 'Frango',
      price: 24.9,
      img: 'imgg',
    },
    bossaNova: {
      id: 4,
      name: 'Bossa Nova',
      type: 'Pernil',
      price: 27.9,
      img: 'imgg',
    },
    abreAlas: {
      id: 5,
      name: 'Abre Alas',
      type: 'Linguiça',
      price: 27.9,
      img: 'imgg',
    },
    miudinho: {
      id: 6,
      name: 'Samba Miudinho',
      type: 'Costela',
      price: 29.9,
      img: 'imgg',
    },
    partidoAlto: {
      id: 7,
      name: 'Partido Alto',
      type: 'Costela',
      price: 36.9,
      img: 'imgg',
    },
    granGalo: {
      id: 8,
      name: 'Gran Galo Cantô',
      type: 'Frango',
      price: 34.9,
      img: 'imgg',
    },
    granBossa: {
      id: 9,
      name: 'Gran Bossa Nova',
      type: 'Perfil',
      price: 37.9,
      img: 'imgg',
    },
    granMiudinho: {
      id: 10,
      name: 'Gran Samba Miudinho',
      type: 'Costela',
      price: 44.9,
      img: 'imgg',
    },
    granPartido: {
      id: 11,
      name: 'Gran Partido Alto',
      type: 'Costela',
      price: 59.9,
      img: 'imgg',
    },
    mocVegFeijao: {
      id: 12,
      name: 'Mocidade Vegetariana de Feijão Fradinho',
      type: 'Vegetariano',
      price: 29.9,
      img: 'imgg',
    },
    mocVegGrao: {
      id: 13,
      name: 'Mocidade Vegetariana de Grão de Bico',
      type: 'Vegetariano',
      price: 29.9,
      img: 'imgg',
    },
    mocVegShitake: {
      id: 14,
      name: 'Mocidade Vegetariana de Shitake',
      type: 'Vegetariano',
      price: 34.9,
      img: 'imgg',
    },
    mocVegDuplo: {
      id: 15,
      name: 'Mocidade Vegetariana Duplo',
      type: 'Vegetariano',
      price: 49.9,
      img: 'imgg',
    },
  },
]

export const lojinha = [
  {
    brownieTrad: {
      id: 1,
      name: 'Brownie Tradicional',
      type: 'Brownie',
      price: 5.9,
      img: 'imgg',
    },
    lays: {
      id: 2,
      name: /Batata Lay's/,
      type: 'Batata',
      price: 8.9,
      img: 'imgg',
    },
    doritos: {
      id: 2,
      name: 'Doritos',
      type: 'Nacho',
      price: 8.9,
      img: 'imgg',
    },
  },
]

// export const rooms = {
//   chicoBuarque: 'Chico Buarque',
//   jovelinaPerolaNegra: 'Jovelina Pérola Negra',
//   noelRosa: 'Noel Rosa',
//   martinhoDaVila: 'Martinho da Vila',
//   bethCarvalho: 'Beth Carvalho',
//   joaoNogueira: 'João Nogueira',
//   almirGuineto: 'Almir Guineto',
//   cartola: 'Cartola',
//   paulinhoDaViola: 'Paulinho da Viola',
// }