import chicoBuarque from '../assets/images/chicoBuarque.jpg'
import noelRosa from '../assets/images/noelRosa.jpg'
import jovelina from '../assets/images/jovelina.jpg'
import martinho from '../assets/images/martinho.jpg'
import beth from '../assets/images/beth.jpg'
import joao from '../assets/images/joao.jpg'
import almir from '../assets/images/almir.jpg'
import cartola from '../assets/images/cartola.jpg'
import paulinho from '../assets/images/paulinho.jpg'

// HOSPEDES
import alex from '../assets/images/hAlex.jpeg'
import matheus from '../assets/images/hMatheus.jpeg'
import marcelo from '../assets/images/hMarcelo.jpeg'
import adelson from '../assets/images/hAdelson.jpeg'
import hiago from '../assets/images/hHiago.jpeg'
import marceloAu from '../assets/images/hMarceloAu.jpeg'
import sylvio from '../assets/images/hSylvio.jpeg'
import fabio from '../assets/images/hFabio.jpeg'



export const rooms = [
  {
    id: 1,
    name: 'Chico Buarque',
    guests: [
      {
        id: 1,
        name: 'Alexsandro',
        lastName: 'Moraes da Rocha',
        email: 'alexmoraes31@gmail.com',
        DDD: 11,
        phoneNumber: 911319252,
        birthYear: 1980,
        birthMounth: 10,
        birthDay: 1,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 455515542,
        expYear: 2025, 
        photo: alex,
      },
      {
        id: 2,
        name: 'Sylvio',
        lastName: 'dos Santos Neto',
        email: 'sylviosnnts@gmail.com',
        DDD: 11,
        phoneNumber: 9930543044,
        birthYear: 1984,
        birthMounth: 9,
        birthDay: 9,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paul',
        docType: 'Identidade',
        docNumber: 401378652,
        expYear: 2025,
        photo: sylvio,
      },
      {
        id: 3,
        name: 'Adelson',
        lastName: 'Gonçalves de Menezes',
        email: 'adelsonmenezes36@gmail.com',
        DDD: 11,
        phoneNumber: 961853696,
        birthYear: 1983,
        birthMounth: 5,
        birthDay: 25,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 37238982,
        expYear: 2025,
        photo: adelson,
      },
      {
        id: 4,
        name: 'Chico',
        lastName: 'Buarque de Holanda',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: chicoBuarque,
      },
    ]
  },
  {
    id: 2,
    name: 'Jovelina Pérola Negra',
    guests: [
      {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: jovelina,
      },
      {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: jovelina,
      },
      {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: jovelina,
      },
      {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: jovelina,
      },
    ]
  },
  {
    id: 3,
    name: 'Noel Rosa',
    guests: [
      {
        id: 1,
        name: 'Marcello',
        lastName: 'Van Moorsel',
        email: 'marcello.moorsel@gmail.com',
        DDD: 11,
        phoneNumber: 999676370,
        birthYear: 1994,
        birthMounth: 9,
        birthDay: 22,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 5800573113,
        expYear: 2025,
        photo: marcelo ? marcelo : noelRosa,
      },
      {
        id: 2,
        name: 'Noel',
        lastName: 'Rosa',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: noelRosa,
      },
      {
        id: 3,
        name: 'Noel',
        lastName: 'Rosa',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: noelRosa,
      },
      {
        id: 4,
        name: 'Noel',
        lastName: 'Rosa',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: noelRosa,
      },
    ]
  },
  {
    id: 4,
    name: 'Martinho da Vila',
    guests: [
      {
        id: 1,
        name: 'Fábio',
        lastName: 'Teodoro',
        email: 'teodorofabio31@gmail.com',
        DDD: 11,
        phoneNumber: 952431452,
        birthYear: 1984,
        birthMounth: 2,
        birthDay: 16,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 6968396304,
        expYear: 2025,
        photo: fabio,
      },
      {
        id: 2,
        name: 'Hiago',
        lastName: 'Luan de Lima',
        email: 'hiagoluan_lima@hotmail.com',
        DDD: 11,
        phoneNumber: 971216430,
        birthYear: 1992,
        birthMounth: 11,
        birthDay: 6,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 485914396,
        expYear: 2025,
        photo: hiago,
      },
      {
        id: 3,
        name: 'Matheus',
        lastName: 'Martiniano do Vale',
        email: 'coohmatheus123@gmail.com',
        DDD: 11,
        phoneNumber: 996320620,
        birthYear: 1999,
        birthMounth: 6,
        birthDay: 17,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 7130140098,
        expYear: 2025,
        photo: matheus,
      },
      {
        id: 4,
        name: 'Marcelo',
        lastName: 'Augusto Moticelli Dias',
        email: 'mmonticeli690@gmail.com',
        DDD: 11,
        phoneNumber: 996932067,
        birthYear: 1993,
        birthMounth: 16,
        birthDay: 6,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'São Paulo',
        city: 'São Paulo',
        docType: 'Identidade',
        docNumber: 488481557,
        expYear: 2025,
        photo: marceloAu,
      },
      {
        id: 5,
        name: 'Martinho',
        lastName: 'da Vila',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: martinho,
      },
      {
        id: 6,
        name: 'Martinho',
        lastName: 'da Vila',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: martinho,
      },
      {
        id: 7,
        name: 'Martinho',
        lastName: 'da Vila',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: martinho,
      },
      {
        id: 8,
        name: 'Martinho',
        lastName: 'da Vila',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: martinho,
      },
    ]
  },
  {
    id: 5,
    name: 'Beth Carvalho',
    guests: [
      {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: beth,
      },
      {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: beth,
      },
      {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: beth,
      },
      {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: beth,
      },
    ]
  },
  {
    id: 6,
    name: 'João Nogueira',
    guests: [
      {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: joao,
      },
      {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: joao,
      },
      {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: joao,
      },
      {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: joao,
      },
    ]
  },
  {
    id: 6,
    name: 'Almir Guineto',
    guests: [
      {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: almir,
      },
      {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: almir,
      },
      {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: almir,
      },
      {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: almir,
      },
    ]
  },
  {
    id: 6,
    name: 'Cartola',
    guests: [
      {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: cartola,
      },
      {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: cartola,
      },
      {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: cartola,
      },
      {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: cartola,
      },
    ]
  },
  {
    id: 6,
    name: 'Paulinho da Viola',
    guests: [
      {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: paulinho,
      },
      {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: paulinho,
      },
      {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: paulinho,
      },
      {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025,
        photo: paulinho,
      },
    ]
  },
]