export const rooms = [
  {
    id: 1,
    name: 'Chico Buarque',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 2,
    name: 'Jovelina Pérola Negra',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 3,
    name: 'Noel Rosa',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 4,
    name: 'Martinho da Vila',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 5,
    name: 'Beth Carvalho',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 6,
    name: 'João Nogueira',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 6,
    name: 'Almir Guineto',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 6,
    name: 'Cartola',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
  {
    id: 6,
    name: 'Paulinho da Viola',
    guests: {
      one: {
        id: 1,
        name: 'Fulano',
        lastName: 'da Silva',
        email: 'fulano@gmailmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      two: {
        id: 2,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      three: {
        id: 3,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
      four: {
        id: 4,
        name: 'Luan',
        lastName: 'da Silva Ramalho',
        email: 'luan.ramalhosilva@gmail.com',
        DDD: 21,
        phoneNumber: 970106538,
        birthYear: 1991,
        birthMounth: 8,
        birthDay: 12,
        genre: 'Masculino',
        country: 'Brasil',
        state: 'Rio de Janeiro',
        city: 'Nilópolis',
        docType: 'Identidade',
        docNumber: 210527800,
        expYear: 2025, 
      },
    }
  },
]